name: Rust

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-aarch64-gnu
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
            source: libducohasher.so
            asset: libducohasher-linux-aarch64.so

          - os-name: Linux-x86_64-gnu
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            source: libducohasher.so
            asset: libducohasher-linux-x86_64.so

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            source: ducohasher.dll
            asset: libducohasher-windows-x86_64.dll

          - os-name: Linux-armv7
            runs-on: ubuntu-24.04
            target: armv7-unknown-linux-gnueabi
            source: libducohasher.so
            asset: libducohasher-linux-armv7.so

          - os-name: Linux-armv7-hf
            runs-on: ubuntu-24.04
            target: armv7-unknown-linux-gnueabihf
            source: libducohasher.so
            asset: libducohasher-linux-armv7-hf.so


    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Publish GitHub release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.platform.asset }}
          generate_release_notes: false
